// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSFTPbRDtS4YUqA5vMhP0PCFIHVNMT3JU',
    appId: '1:452503015485:ios:cc38a757f959e1d1c0da54',
    messagingSenderId: '452503015485',
    projectId: 'starnutri-f9b6f',
    storageBucket: 'starnutri-f9b6f.firebasestorage.app',
    iosBundleId: 'com.example.starnutri',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7ZwSy7sWockvfuPfd8D3YuOKwk48L1rc',
    appId: '1:452503015485:web:9a5980bccc15490fc0da54',
    messagingSenderId: '452503015485',
    projectId: 'starnutri-f9b6f',
    authDomain: 'starnutri-f9b6f.firebaseapp.com',
    storageBucket: 'starnutri-f9b6f.firebasestorage.app',
    measurementId: 'G-30NGPYFG1Y',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7ZwSy7sWockvfuPfd8D3YuOKwk48L1rc',
    appId: '1:452503015485:web:9a5980bccc15490fc0da54',
    messagingSenderId: '452503015485',
    projectId: 'starnutri-f9b6f',
    authDomain: 'starnutri-f9b6f.firebaseapp.com',
    storageBucket: 'starnutri-f9b6f.firebasestorage.app',
    measurementId: 'G-30NGPYFG1Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSFTPbRDtS4YUqA5vMhP0PCFIHVNMT3JU',
    appId: '1:452503015485:ios:cc38a757f959e1d1c0da54',
    messagingSenderId: '452503015485',
    projectId: 'starnutri-f9b6f',
    storageBucket: 'starnutri-f9b6f.firebasestorage.app',
    iosBundleId: 'com.example.starnutri',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0N8Ww3ufzePEijEg854rTIctQJAw7IM4',
    appId: '1:452503015485:android:db68cf33377de414c0da54',
    messagingSenderId: '452503015485',
    projectId: 'starnutri-f9b6f',
    storageBucket: 'starnutri-f9b6f.firebasestorage.app',
  );

}